# fly.toml app configuration file generated for fitlab-api on 2026-05-02T22:30:30-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fitlab-api'
primary_region = 'gru'

[build]
  [build.args]
    GO_VERSION = '1.21'

[env]
  ALLOWED_ORIGINS = 'https://fitab-lime.vercel.app'
  DATABASE_PATH = '/data/fitlab.db'
  DEV_MODE = 'false'
  PORT = '8080'

[[mounts]]
  source = 'fitlab_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
